apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
images:
  - name: pratiksha0111/easy-backend
    newTag: dev-latest
  - name: pratiksha0111/easy-frontend
    newTag: dev-latest
